# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  GO_VERSION: 1.19

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION}}

      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: |
          make

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Set up Go 1.x.y
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Test
        shell: bash
        run: |
          make ut

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./unittest-coverage.out

  bench:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION}}

      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: |
          make bench
